PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
ANALYZE sqlite_master;

CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT, username CHAR(255), email CHAR(255), hashed_password CHAR(255));
CREATE TABLE IF NOT EXISTS sessions(id CHAR(255) NOT NULL, user_id INT NOT NULL, created_at DATETIME NOT NULL);
CREATE TABLE IF NOT EXISTS posts (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INT NOT NULL, content TEXT NOT NULL, created_at DATETIME NOT NULL);
CREATE TABLE IF NOT EXISTS comments (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INT NOT NULL, post_id INT NOT NULL, content TEXT, created_at DATETIME NOT NULL);
CREATE TABLE IF NOT EXISTS post_favorites (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INT NOT NULL, post_id INT NOT NULL);
CREATE TABLE IF NOT EXISTS submissions (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INT NOT NULL, repo TEXT NOT NULL, created_at DATETIME NOT NULL);

COMMIT;
